preload = /home/doku/Downloads/wallpaperflare.com_wallpaper.jpg
# .. more preloads
#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = ,/home/doku/Downloads/wallpaperflare.com_wallpaper.jpg
# .. more monitors
 
#enable splash text rendering over the wallpaper
splash = false
 
#fully disable ipc
# ipc = off
